### ISSUE TITLE
不怕云脉找你麻烦吗， 搞个马甲就收费， 小伙伴们小心花了钱还惹麻烦

### ISSUE THREAD

**Issue by 153437803** [XieZhiFa/IdCardOCR#12]
![TIM截图20191121150906](https://user-images.githubusercontent.com/10386505/69315251-0997c300-0c71-11ea-8e6b-ae5239072ec8.png)
<img width="496" alt="微信截图_20191121150926" src="https://user-images.githubusercontent.com/10386505/69315254-0997c300-0c71-11ea-8a68-6d8a413f7820.png">

**Comment by XieZhiFa** [comment]
是吗？
