### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by liganggit** [XieZhiFa/IdCardOCR#2]
问一下 这个库哪来的？ library-ocr-1.0.4-SNAPSHOT.aar

**Comment by XieZhiFa** [comment]
自己封装

**Comment by liganggit** [comment]
我意思是 library-ocr 里面的使用的so是哪里的？

**Comment by liganggit** [comment]
有源码可以研究么？卡片信息提取时，预处理上花费了很多时间但是效果都不好，阴影光线背景环境等等的影响，不知道有什么好的方式。

**Comment by liganggit** [comment]
比如 com.msd.ocr   com.ym.ocr 这俩包以及对so的封装有来源吗？
