### ISSUE TITLE
请问不需要驾驶证识别怎么去除

### ISSUE THREAD

**Issue by dingzhixiang** [XieZhiFa/IdCardOCR#26]
包太大了，请问不需要驾驶证识别怎么去除

**Comment by XieZhiFa** [comment]
把.aar改为.zip, （注意不要解压， 直接用winRAR软件双击打开）删除
arm64-v8a/libDrivingPermit.so
armeabi/libDrivingPermit.so 
armeabi-7a/libDrivingPermit.so 
x86/libDrivingPermit.so
然后再把 .zip改为 .aar即可。
