### ISSUE TITLE
请问图片解码是怎么做的

### ISSUE THREAD

**Issue by HughQuain** [XieZhiFa/IdCardOCR#27]
好像找不到代码

**Comment by wangjing71** [comment]
用的其他公司的so包，你也可以直接把aar下载下来，用7.zip打开，删除里面的一个授权class文件，自己用同名的类和方法方法永远返回true,替换掉就可以免费试用，商用有风险

**Comment by HughQuain** [comment]
好的，非常感谢！------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Wiggins.Wang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月31日(星期四) 上午10:53
收件人:&nbsp;&quot;XieZhiFa/IdCardOCR&quot;<IdCardOCR@noreply.github.com&gt;;
抄送:&nbsp;&quot;HughQuain&quot;<986610875@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [XieZhiFa/IdCardOCR] 请问图片解码是怎么做的 (#27)
