### ISSUE TITLE
识别速度慢的问题

### ISSUE THREAD

**Issue by QiuShanwen** [XieZhiFa/IdCardOCR#35]
用你的SimpleCameraActivity识别会很慢，后面发现ViewfinderView的getFinder()这个方法写错了，不知道你抄谁的，导致识别范围都不对，改成return new Rect((int)(this.lineLeft), (int)(this.lineTop ), (int)(this.lineRight), (int)(this.lineBottom));就好了

**Comment by XieZhiFa** [comment]
不同的手机可能相机角度不对，后面版本优化了。
