### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by ALittleDruid** [XieZhiFa/IdCardOCR#48]
调用OcrDecode.decode(byte[] var1, Rect var2, OcrDecodeCallback var3);
var1是一张1280*720的身份证图片
Utils.matToBitmap(src, bitmap);
ByteArrayOutputStream bs = new ByteArrayOutputStream();
bitmap.compress(Bitmap.CompressFormat.JPEG, 100, bs);
ocrDecode.decode(bs.toByteArray(), null, callback);
try {
    bs.close();
} catch (IOException e) {
    Log.e(TAG, "decode: ", e);
}
调用100次,内存大约增长250M
调用OcrDecode.close();也不能释放这部分内存
识别了大概400次就OOM了
希望能解决这个问题

**Comment by XieZhiFa** [comment]
用Android studio 中的Android Profiler测试过是内存泄露吗

**Comment by ALittleDruid** [comment]
> 用Android studio 中的Android Profiler测试过是内存泄露吗

[MainActivity.zip](https://github.com/user-attachments/files/16569045/MainActivity.zip)

MainActivity改了下，点击开始扫描按钮，开始连续识别100次/sdcard/sfz.png这张图片
这张图片是你的示例身份证图片，宽和高直接拉伸成原来的三倍
连续识别400次后Android Profiler的结果

<img width="680" alt="sfz" src="https://github.com/user-attachments/assets/b23ce582-1035-4a5d-aa31-1bf0c4bc25a0">

![image](https://github.com/user-attachments/assets/bb499c3a-f2ed-4975-bab6-d7dc6a8b3e7b)
![image](https://github.com/user-attachments/assets/dd76deda-78ff-431a-bd8c-a1ae22b93078)

**Comment by XieZhiFa** [comment]
没用调用 ocrDecode.close(); 释放资源
