### ISSUE TITLE
既然收费，干嘛不用阿里百度的识别，人家还有免费的次数能用。。。。

### ISSUE THREAD

**Issue by Kevin20145** [XieZhiFa/IdCardOCR#7]

**Comment by XieZhiFa** [comment]
嗯是的, 但是这个是离线识别,不需要网络,不限制次数.

**Comment by Kevin20145** [comment]
百度阿里也不用联网的而且你这个500也够贵的，500买了，能买到源码吗？

**Comment by DLTech21** [comment]
不用买了，就是破解云脉的sdk

**Comment by wangjing71** [comment]
> 不用买了，就是破解云脉的sdk

用的其他公司的so包，你也可以直接把aar下载下来，用7.zip打开，删除里面的一个授权class文件，自己用同名的类和方法方法永远返回true,替换掉就可以免费试用，商用有风险
